### ISSUE TITLE
Why main not working ?

### ISSUE THREAD

**Issue by GaganHonor** [reallyabcd/top_programming_languages#3]
pip install requests beautifulsoup4
`import requests
from bs4 import BeautifulSoup

url = 'https://www.hackerrank.com/blog/the-15-most-popular-programming-languages-of-2023/'
page = requests.get(url)
soup = BeautifulSoup(page.content, 'html.parser')
languages = soup.find_all('h3')[1:16]

print('Top Programming Languages in 2023:')
for language in languages:
    print(language.text)
`

**Comment by reallyabcd** [comment]
issue is api is outdated

**Comment by GaganHonor** [comment]
ok
