### ISSUE TITLE
Which is working 

### ISSUE THREAD

**Issue by reallyabcd** [reallyabcd/top_programming_languages#4]
which py works

**Comment by GaganHonor** [comment]
The import requests
import json
`
def get_top_languages():
    print("Welcome to the Top Programming Languages tool!")
    print("Please choose from the following options to customize your query:")
    print("1. Time range")
    print("2. Location")
    print("3. Language")
    print("4. Sort by")
    print("5. Order")
    print("6. Search")

    time_range = ''
    location = ''
    language = ''
    sort_by = ''
    order = ''

    while True:
        choice = input("Enter your choice (1-6): ")
        if choice == '1':
            time_range = input("Enter the time range (e.g., 'last year', 'last month', 'last week'): ")
        elif choice == '2':
            location = input("Enter the location (e.g., 'United States', 'India', 'China'): ")
        elif choice == '3':
            language = input("Enter the language (e.g., 'Python', 'Java', 'JavaScript'): ")
        elif choice == '4':
            sort_by = input("Enter the sort by criteria (e.g., 'stars', 'forks', 'updated'): ")
        elif choice == '5':
            order = input("Enter the order (e.g., 'asc', 'desc'): ")
        elif choice == '6':
            break
        else:
            print("Invalid choice, please try again.")

    query = f'https://api.github.com/search/repositories?q=language:{language}'

    if time_range:
        query += f'+created:{time_range}'
    if location:
        query += f'+location:{location}'
    if sort_by:
        query += f'&sort={sort_by}'
    if order:
        query += f'&order={order}'

    response = requests.get(query)
    data = json.loads(response.text)
    languages = {}

    for item in data['items']:
        language = item['language']
        if language not in languages:
            languages[language] = 0
        languages[language] += 1

    sorted_languages = sorted(languages.items(), key=lambda x: x[1], reverse=True)

    print("\nHere are the top programming languages according to your query:")
    for i, language in enumerate(sorted_languages):
        print(f"{i + 1}. {language[0]} ({language[1]} repositories)")

while True:
    get_top_languages()
    choice = input("\nDo you want to perform another search? (y/n): ")
    if choice.lower() != 'y':
        break
   `

is working ❤️❤️❤️❤️
